version: '3.7'
services:
  quiz-back:
    build: ./quizz-service
    ports:
      - 3001:3001
    environment:
      PORT: 3001
  front:
  
    build: 
      context: ./front
      args:
        - BASE_API=http://quiz-back:3001
    ports:
      - 3000:3000
    environment:
      BASE_API: http://quiz-back:3001
    depends_on:
      - quiz-back